### ISSUE TITLE
unum_log not implemented?

### ISSUE THREAD

**Issue by HughAndersonNUS** [LLNL/unum#2]
Hi,

I note that unum_log does not appear to be in the library, although it appears in the unum.h file. Is this correct?
Cheers Hugh

**Comment by gslloyd** [comment]
The header files unum.h, ubnd.h, gbnd.h contain many function declarations that serve as place holders for those that have not yet been implemented in the corresponding .c files. A map of functions is shown in doc/modules.pptx which indicates the unimplemented functions in red. Transcendental functions have not been implemented and unum_log falls into this category.
